DebugModeConfiguration:

  # The key used to step through code
  stepKey: F10

  # The key used to step over function call
  stepOverKey: F9

  # Whether to automatically step over NOPs after a RET instruction
  doStepOverNOPsAfterRET: true