DebugModeConfiguration:

  # The key used to step through code
  stepKey: F1

  # The key used to step over function call
  stepOverKey: F2

  # Whether to automatically step over NOPs after a RET instruction
  doStepOverNOPsAfterRET: false